import * as fs from 'fs';
import { InMemoryGraph } from './InMemoryGraph';
import { Node, Edge } from './types';

export interface GraphDataPayload {
  files: string[];
  symbols: Node[];
  relationships: Edge[];
}

export class GraphLoader {
  /**
   * Loads graph data from a JSON file and populates the InMemoryGraph.
   * @param filePath The path to the JSON file generated by Developer 1.
   * @param graph The InMemoryGraph instance to populate.
   */
  public static loadFromJson(filePath: string, graph: InMemoryGraph): void {
    if (!fs.existsSync(filePath)) {
      throw new Error(`Cannot find graph data file at: ${filePath}`);
    }

    const rawData = fs.readFileSync(filePath, 'utf-8');
    const parsedData = JSON.parse(rawData) as GraphDataPayload;

    // 1. Load Symbols (Nodes)
    if (parsedData.symbols && Array.isArray(parsedData.symbols)) {
      for (const symbol of parsedData.symbols) {
        graph.addNode(symbol);
      }
    } else {
      console.warn("No 'symbols' array found in the input data.");
    }

    // 2. Load Relationships (Edges)
    if (parsedData.relationships && Array.isArray(parsedData.relationships)) {
      for (const relation of parsedData.relationships) {
        try {
          graph.addEdge(relation);
        } catch (e: any) {
          console.warn(`Skipping invalid edge: ${e.message}`);
        }
      }
    } else {
      console.warn("No 'relationships' array found in the input data.");
    }
  }
}
