import * as fs from 'fs';
import { InMemoryGraph } from './InMemoryGraph';
import { Node, Edge } from './types';

export interface GraphDataPayload {
  files: string[];
  symbols: Node[];
  relationships: Edge[];
}

type RawSymbol = Partial<Node> & {
  id?: string;
  file?: string;
};

export class GraphLoader {
  /**
   * Loads graph data from a JSON file and populates the InMemoryGraph.
   * @param filePath The path to the JSON file generated by Developer 1.
   * @param graph The InMemoryGraph instance to populate.
   */
  public static loadFromJson(filePath: string, graph: InMemoryGraph): void {
    if (!fs.existsSync(filePath)) {
      throw new Error(`Cannot find graph data file at: ${filePath}`);
    }

    const rawData = fs.readFileSync(filePath, 'utf-8');
    const parsedData = JSON.parse(rawData) as Partial<GraphDataPayload> & {
      symbols?: RawSymbol[];
    };

    const nodeIdsByName = new Map<string, string>();

    for (const filePath of parsedData.files ?? []) {
      graph.addNode({ id: filePath, type: 'FILE', name: filePath, filePath });
      nodeIdsByName.set(filePath, filePath);
    }

    // 1. Load Symbols (Nodes)
    if (parsedData.symbols && Array.isArray(parsedData.symbols)) {
      for (const symbol of parsedData.symbols) {
        const name = symbol.name;
        if (!name) continue;

        const node: Node = {
          id: symbol.id ?? name,
          type: String(symbol.type ?? 'FUNCTION').toUpperCase() as Node['type'],
          name,
          filePath: symbol.filePath ?? symbol.file,
          startLine: symbol.startLine,
          endLine: symbol.endLine
        };
        graph.addNode(node);
        nodeIdsByName.set(name, node.id);
      }
    } else {
      console.warn("No 'symbols' array found in the input data.");
    }

    // 2. Load Relationships (Edges)
    if (parsedData.relationships && Array.isArray(parsedData.relationships)) {
      for (const relation of parsedData.relationships) {
        try {
          // Attempt strict lookup
          let fromId = nodeIdsByName.get(relation.from);
          let toId = nodeIdsByName.get(relation.to);

          // Fuzzy fallback for Tree-sitter AST issues (e.g., "this.methodName" or "Class.methodName")
          if (!fromId && typeof relation.from === 'string' && relation.from.includes('.')) {
            const fromParts = relation.from.split('.');
            fromId = nodeIdsByName.get(fromParts[fromParts.length - 1]);
          }
          if (!toId && typeof relation.to === 'string' && relation.to.includes('.')) {
            const toParts = relation.to.split('.');
            toId = nodeIdsByName.get(toParts[toParts.length - 1]);
          }

          const edge = {
            ...relation,
            from: fromId ?? relation.from,
            to: toId ?? relation.to
          };
          
          graph.addEdge(edge);
        } catch (e: any) {
          console.warn(`Skipping invalid edge: ${e.message}`);
        }
      }
    } else {
      console.warn("No 'relationships' array found in the input data.");
    }
  }
}
