import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import dotenv from "dotenv";
import * as fs from "fs";
import * as path from "path";
import { InMemoryGraph } from "../graph/InMemoryGraph.js";
import { GraphLoader } from "../graph/GraphLoader.js";
import { GraphQueryEngine } from "../graph/GraphQueryEngine.js";
import { Node } from "../graph/types.js";

// Load environment variables if needed
dotenv.config();

export class AGCPMCPServer {
  private server: Server;
  private graphEngine!: GraphQueryEngine;

  constructor() {
    this.server = new Server(
      {
        name: "agcp-mcp-server",
        version: "1.0.0",
      },
      {
        capabilities: { tools: {} },
      }
    );

    this.initGraph();
    this.setupHandlers();
  }

  private initGraph() {
    try {
      const graph = new InMemoryGraph();
      // Load the data generated by Developer 1
      const dataPath = path.resolve(process.cwd(), "data/output.json");
      
      if (fs.existsSync(dataPath)) {
        GraphLoader.loadFromJson(dataPath, graph);
        console.error(`[AGCP] Successfully loaded graph from ${dataPath}`);
      } else {
        console.error(`[AGCP] Warning: No graph data found at ${dataPath}. Please ensure Developer 1 output exists.`);
      }
      
      this.graphEngine = new GraphQueryEngine(graph);
    } catch (error) {
      console.error("[AGCP] Failed to initialize Graph Engine:", error);
      // Initialize with empty graph as fallback so the server doesn't crash
      this.graphEngine = new GraphQueryEngine(new InMemoryGraph());
    }
  }

  /**
   * Helper function to extract exact lines of code from the file system.
   */
  private extractCodeSnippet(node: Node): string {
    if (!node.filePath) return "";
    
    try {
      // Assuming paths in the graph are relative to the project root
      const absolutePath = path.resolve(process.cwd(), node.filePath);
      if (!fs.existsSync(absolutePath)) return `// File not found on disk: ${node.filePath}`;
      
      const fileContent = fs.readFileSync(absolutePath, "utf-8");
      
      // If we don't have line numbers, return the whole file
      if (node.startLine === undefined || node.endLine === undefined) {
        return fileContent;
      }
      
      const lines = fileContent.split("\n");
      // startLine and endLine are 1-indexed in Developer 1's parser
      const startIdx = Math.max(0, node.startLine - 1);
      const endIdx = Math.min(lines.length, node.endLine);
      
      return lines.slice(startIdx, endIdx).join("\n");
    } catch (error) {
      console.error(`[AGCP] Error reading file ${node.filePath}:`, error);
      return `// Error reading file: ${node.filePath}`;
    }
  }

  private setupHandlers() {
    // List available tools
    this.server.setRequestHandler(ListToolsRequestSchema, async () => {
      return {
        tools: [
          {
            name: "getContext",
            description: "Fetches minimal code context for a given query using the AGCP Graph Planner. Use this tool when you need to understand the codebase structure and get the exact lines of code needed to fulfill the user's request.",
            inputSchema: {
              type: "object",
              properties: {
                query: {
                  type: "string",
                  description: "The user's natural language query (e.g. 'I need to add dark mode').",
                },
              },
              required: ["query"],
            },
          },
        ],
      };
    });

    // Handle tool execution
    this.server.setRequestHandler(CallToolRequestSchema, async (request) => {
      const { name, arguments: args } = request.params;

      if (name === "getContext") {
        const query = String(args?.query);
        
        try {
          // 1. Ask the engine to plan the context (max depth 3)
          const plan = this.graphEngine.planContext(query, 3);
          
          if (plan.status === 'not-found') {
            return {
              content: [
                {
                  type: "text",
                  text: JSON.stringify({
                    status: "not-found",
                    message: `Could not find any relevant codebase symbols matching the query: '${query}'.`
                  }, null, 2)
                }
              ]
            };
          }

          // 2. Extract real code snippets for every node the graph engine found
          const fileContexts = plan.nodes
            .filter(node => node.filePath) // Ignore virtual nodes without files
            .map(node => ({
              symbol: node.name,
              type: node.type,
              filePath: node.filePath,
              startLine: node.startLine,
              endLine: node.endLine,
              code: this.extractCodeSnippet(node) // The magic happens here!
            }));
          
          // 3. Return the optimized payload to the IDE Agent
          return {
            content: [
              {
                type: "text",
                text: JSON.stringify({
                  status: plan.status,
                  targetSymbol: plan.target?.name,
                  maxDepthReached: plan.maxDepth,
                  extractedContext: fileContexts
                }, null, 2),
              },
            ],
          };
        } catch (error: any) {
          return {
            content: [
              {
                type: "text",
                text: JSON.stringify({ status: "error", message: error.message })
              }
            ],
            isError: true
          };
        }
      }

      throw new Error(`Unknown tool: ${name}`);
    });
  }

  public async start() {
    // Setup STDIO transport for MCP
    const transport = new StdioServerTransport();
    await this.server.connect(transport);
    console.error("[AGCP] Context Server running on stdio");
  }
}
