import * as path from 'path';
import { InMemoryGraph } from './graph/InMemoryGraph';
import { GraphLoader } from './graph/GraphLoader';
import { GraphQueryEngine } from './graph/GraphQueryEngine';

export { InMemoryGraph, GraphLoader, GraphQueryEngine };
function main() {
  console.log('--- AGCP Graph Engine ---');
  
  // The path to the JSON output generated by Developer 1
  // You can pass the path as a command line argument, e.g., `npm start -- ./data/output.json`
  const inputFilePath = process.argv[2] || path.join(__dirname, '../data/output.json');

  console.log(`Attempting to load graph data from: ${inputFilePath}`);

  const graph = new InMemoryGraph();

  try {
    GraphLoader.loadFromJson(inputFilePath, graph);

    console.log('\n--- Graph State ---');
    console.log(`Total Nodes: ${graph.getAllNodes().length}`);
    console.log(`Total Edges: ${graph.getAllEdges().length}`);

    const queryEngine = new GraphQueryEngine(graph);
    console.log('\n--- Graph Query Engine Ready ---\n');

    const formatNodes = (nodes: any[]) => nodes.map(n => `[${n.type}] ${n.name}`).join(', ');

    // Example Relations (Day 4)
    console.log('--- Relations (Day 4) ---');
    console.log('findNode("loginUser") ->', formatNodes(queryEngine.findNode('loginUser')));
    console.log('getCallees("m1") ->', formatNodes(queryEngine.getCallees('m1')));
    console.log('getReferences("c1") ->', formatNodes(queryEngine.getReferences('c1')));

    // Example BFS Context Expansion (Day 5)
    console.log('\n--- BFS Context Expansion (Day 5) ---');
    console.log('Expanding context for "loginUser" (m1) to max depth 2:');
    const expansion = queryEngine.getContextExpansion('m1', 2);
    expansion.forEach(layer => {
      console.log(`Depth ${layer.depth} -> [${formatNodes(layer.nodes)}]`);
    });

  } catch (error: any) {
    console.error(`\n[ERROR] Failed to load graph: ${error.message}`);
    console.error(`Please make sure Developer 1 has generated the JSON output and provide the correct file path.`);
    console.error(`Usage: npm start <path/to/data.json>`);
  }
}

main();
