import * as path from 'path';
import { InMemoryGraph } from './graph/InMemoryGraph';
import { GraphLoader } from './graph/GraphLoader';

function main() {
  console.log('--- AGCP Graph Engine ---');
  
  // The path to the JSON output generated by Developer 1
  // You can pass the path as a command line argument, e.g., `npm start -- ./data/output.json`
  const inputFilePath = process.argv[2] || path.join(__dirname, '../../data/output.json');

  console.log(`Attempting to load graph data from: ${inputFilePath}`);

  const graph = new InMemoryGraph();

  try {
    GraphLoader.loadFromJson(inputFilePath, graph);

    console.log('\n--- Graph State ---');
    console.log(`Total Nodes: ${graph.getAllNodes().length}`);
    console.log(`Total Edges: ${graph.getAllEdges().length}`);

    // You can query specific nodes here later
    // console.log(graph.getNode('file:src/auth.ts'));

  } catch (error: any) {
    console.error(`\n[ERROR] Failed to load graph: ${error.message}`);
    console.error(`Please make sure Developer 1 has generated the JSON output and provide the correct file path.`);
    console.error(`Usage: npm start <path/to/data.json>`);
  }
}

main();
