import * as path from 'path';
import { InMemoryGraph } from './graph/InMemoryGraph';
import { GraphLoader } from './graph/GraphLoader';
import { DEFAULT_MAX_DEPTH, GraphQueryEngine } from './graph/GraphQueryEngine';

export { InMemoryGraph, GraphLoader, GraphQueryEngine };
export { DEFAULT_MAX_DEPTH } from './graph/GraphQueryEngine';
export type { AdaptiveContextItem, ContextPlan, TargetResolution } from './graph/GraphQueryEngine';
function main() {
  console.log('--- AGCP Graph Engine ---');
  
  // The path to the JSON output generated by Developer 1
  // You can pass the path as a command line argument, e.g., `npm start -- ./data/output.json`
  const inputFilePath = process.argv[2] || path.join(__dirname, '../data/output.json');

  console.log(`Attempting to load graph data from: ${inputFilePath}`);

  const graph = new InMemoryGraph();

  try {
    GraphLoader.loadFromJson(inputFilePath, graph);

    console.log('\n--- Graph State ---');
    console.log(`Total Nodes: ${graph.getAllNodes().length}`);
    console.log(`Total Edges: ${graph.getAllEdges().length}`);

    const queryEngine = new GraphQueryEngine(graph);
    console.log('\n--- Graph Query Engine Ready ---\n');

    const formatNodes = (nodes: any[]) => nodes.map(n => `[${n.type}] ${n.name}`).join(', ');

    console.log('--- Context Planning (Day 5) ---');
    const plan = queryEngine.planContext('Modify login() logic');
    console.log(`planContext("Modify login() logic") -> ${plan.status}`);
    console.log(`Target: ${plan.target ? `[${plan.target.type}] ${plan.target.name}` : 'none'}`);
    console.log(`Selected symbols: ${plan.selectedSymbols.join(', ') || 'none'}`);
    plan.context.forEach(item => {
      const via = item.via ? ` via ${item.via}` : '';
      console.log(`Depth ${item.depth}${via} -> [${formatNodes([item.node])}]`);
    });

  } catch (error: any) {
    console.error(`\n[ERROR] Failed to load graph: ${error.message}`);
    console.error(`Please make sure Developer 1 has generated the JSON output and provide the correct file path.`);
    console.error(`Usage: npm start <path/to/data.json>`);
  }
}

main();
